/*
# Seed micro categories for original 10 catalog macro categories

## Problem
The original 10 catalog_macro_categories (Ristorazione, Alloggio, Artigianato, Commercio,
Servizi Professionali, Salute e Benessere, Trasporti, Istruzione, Agricoltura, Industria)
have 0 micro categories because their slugs don't match any old business_categories parent slugs.

## Solution
1. Map old business_categories children to the original 10 macros via semantic mapping
2. Seed new micro categories directly for macros that still have 0 children

## Tables affected
- catalog_micro_categories: populated for the original 10 macro categories
*/

-- Step 1: Remap old business_categories children to original 10 catalog macros
WITH mapping(old_parent_slug, macro_slug) AS (
  VALUES
    ('artigiani', 'artigianato'),
    ('salute', 'salute-benessere'),
    ('benessere', 'salute-benessere'),
    ('studi-professionali', 'servizi-professionali'),
    ('consulenza', 'servizi-professionali'),
    ('formazione', 'istruzione'),
    ('edilizia', 'artigianato'),
    ('casa-e-servizi', 'artigianato'),
    ('turismo', 'alloggio'),
    ('automotive', 'trasporti'),
    ('sport-e-fitness', 'salute-benessere'),
    ('informatica', 'servizi-professionali'),
    ('finanza', 'servizi-professionali'),
    ('immobiliare', 'servizi-professionali'),
    ('marketing-e-creator', 'servizi-professionali'),
    ('servizi-digitali', 'servizi-professionali'),
    ('media', 'servizi-professionali'),
    ('ricerca', 'servizi-professionali'),
    ('animali', 'commercio'),
    ('infanzia', 'commercio'),
    ('gaming', 'commercio'),
    ('enti-e-associazioni', 'servizi-professionali'),
    ('assistenza', 'servizi-professionali'),
    ('energia', 'industria')
)
INSERT INTO catalog_micro_categories (macro_category_id, name, slug, sort_order, is_active)
SELECT cmc.id, child.name, child.slug,
  ROW_NUMBER() OVER (PARTITION BY cmc.id ORDER BY child.name) - 1,
  true
FROM business_categories child
JOIN business_categories parent ON child.parent_id = parent.id
JOIN mapping ON parent.slug = mapping.old_parent_slug
JOIN catalog_macro_categories cmc ON cmc.slug = mapping.macro_slug
WHERE child.is_catalog_v2 = false
ON CONFLICT DO NOTHING;

-- Step 2: Seed micro categories directly for macros that still have 0 children
INSERT INTO catalog_micro_categories (macro_category_id, name, slug, sort_order, is_active)
SELECT cmc.id, mc.name, mc.slug, mc.sort_order, true
FROM catalog_macro_categories cmc
JOIN (VALUES
  ('ristorazione', 'Ristorante', 'ristorante', 0),
  ('ristorazione', 'Trattoria', 'trattoria', 1),
  ('ristorazione', 'Pizzeria', 'pizzeria', 2),
  ('ristorazione', 'Bar', 'bar', 3),
  ('ristorazione', 'Gelateria', 'gelateria', 4),
  ('ristorazione', 'Pasticceria', 'pasticceria', 5),
  ('ristorazione', 'Enoteca', 'enoteca', 6),
  ('ristorazione', 'Agriturismo', 'agriturismo-risto', 7),
  ('ristorazione', 'Self-service', 'self-service', 8),
  ('ristorazione', 'Fast food', 'fast-food', 9),
  ('ristorazione', 'Caffetteria', 'caffetteria', 10),
  ('ristorazione', 'Birreria', 'birreria', 11),
  ('ristorazione', 'Pub', 'pub', 12),
  ('ristorazione', 'Sushi bar', 'sushi-bar', 13),
  ('ristorazione', 'Braceria', 'braceria', 14),
  ('ristorazione', 'Creperia', 'creperia', 15),
  ('ristorazione', 'Rosticceria', 'rosticceria', 16),
  ('ristorazione', 'Tavola calda', 'tavola-calda', 17),
  ('alloggio', 'Hotel', 'hotel', 0),
  ('alloggio', 'Bed and Breakfast', 'bed-and-breakfast', 1),
  ('alloggio', 'Agriturismo', 'agriturismo-alloggio', 2),
  ('alloggio', 'Casa vacanze', 'casa-vacanze', 3),
  ('alloggio', 'Residence', 'residence', 4),
  ('alloggio', 'Ostello', 'ostello', 5),
  ('alloggio', 'Motel', 'motel-alloggio', 6),
  ('alloggio', 'Campeggio', 'campeggio', 7),
  ('alloggio', 'Chalet', 'chalet-alloggio', 8),
  ('alloggio', 'Affittacamere', 'affittacamere', 9),
  ('artigianato', 'Falegname', 'falegname-art', 0),
  ('artigianato', 'Elettricista', 'elettricista-art', 1),
  ('artigianato', 'Idraulico', 'idraulico-art', 2),
  ('artigianato', 'Muratore', 'muratore-art', 3),
  ('artigianato', 'Imbianchino', 'imbianchino-art', 4),
  ('artigianato', 'Piastrellista', 'piastrellista-art', 5),
  ('artigianato', 'Fabbro', 'fabbro-art', 6),
  ('artigianato', 'Serramentista', 'serramentista-art', 7),
  ('artigianato', 'Cartongessista', 'cartongessista-art', 8),
  ('artigianato', 'Restauro', 'restauro-art', 9),
  ('artigianato', 'Artigiano artistico', 'artigiano-artistico', 10),
  ('commercio', 'Alimentari', 'alimentari-comm', 0),
  ('commercio', 'Abbigliamento', 'abbigliamento-comm', 1),
  ('commercio', 'Elettronica', 'elettronica-comm', 2),
  ('commercio', 'Arredamento', 'arredamento-comm', 3),
  ('commercio', 'Giocattoli', 'giocattoli-comm', 4),
  ('commercio', 'Illuminazione', 'illuminazione-comm', 5),
  ('commercio', 'Orologeria', 'orologeria-comm', 6),
  ('commercio', 'Colorificio', 'colorificio-comm', 7),
  ('commercio', 'Ferramenta', 'ferramenta', 8),
  ('commercio', 'Cartolibreria', 'cartolibreria', 9),
  ('commercio', 'Profumeria', 'profumeria', 10),
  ('commercio', 'Ottico', 'ottico-comm', 11),
  ('commercio', 'Farmacia', 'farmacia-comm', 12),
  ('commercio', 'Macelleria', 'macelleria-comm', 13),
  ('commercio', 'Pescheria', 'pescheria-comm', 14),
  ('commercio', 'Latteria', 'latteria-comm', 15),
  ('commercio', 'Fruttivendolo', 'fruttivendolo', 16),
  ('commercio', 'Panetteria', 'panetteria', 17),
  ('commercio', 'Torrefazione', 'torrefazione-comm', 18),
  ('commercio', 'Distilleria', 'distilleria-comm', 19),
  ('commercio', 'Negozio animali', 'negozio-animali-comm', 20),
  ('servizi-professionali', 'Consulenza aziendale', 'consulenza-aziendale', 0),
  ('servizi-professionali', 'Consulenza legale', 'consulenza-legale', 1),
  ('servizi-professionali', 'Consulenza fiscale', 'consulenza-fiscale-serv', 2),
  ('servizi-professionali', 'Consulenza del lavoro', 'consulenza-del-lavoro', 3),
  ('servizi-professionali', 'Agenzia del lavoro', 'agenzia-del-lavoro-serv', 4),
  ('servizi-professionali', 'Informatica', 'informatica-serv', 5),
  ('servizi-professionali', 'Marketing', 'marketing-serv', 6),
  ('servizi-professionali', 'Grafica', 'grafica', 7),
  ('servizi-professionali', 'Finanza', 'finanza-serv', 8),
  ('servizi-professionali', 'Immobiliare', 'immobiliare-serv', 9),
  ('servizi-professionali', 'Assicurazioni', 'assicurazioni', 10),
  ('servizi-professionali', 'Traduzioni', 'traduzioni', 11),
  ('servizi-professionali', 'Architettura', 'architettura', 12),
  ('servizi-professionali', 'Ingegneria', 'ingegneria', 13),
  ('servizi-professionali', 'Geometra', 'geometra', 14),
  ('servizi-professionali', 'Notaio', 'notaio', 15),
  ('salute-benessere', 'Medico di base', 'medico-di-base', 0),
  ('salute-benessere', 'Dentista', 'dentista-salute', 1),
  ('salute-benessere', 'Farmacia', 'farmacia-salute', 2),
  ('salute-benessere', 'Ottico', 'ottico-salute', 3),
  ('salute-benessere', 'Fisioterapista', 'fisioterapista', 4),
  ('salute-benessere', 'Psicologo', 'psicologo', 5),
  ('salute-benessere', 'Osteopata', 'osteopata', 6),
  ('salute-benessere', 'Chiropratico', 'chiropratico', 7),
  ('salute-benessere', 'Parrucchiere', 'parrucchiere-salute', 8),
  ('salute-benessere', 'Barbiere', 'barbiere-salute', 9),
  ('salute-benessere', 'Estetista', 'estetista', 10),
  ('salute-benessere', 'Centro estetico', 'centro-estetico', 11),
  ('salute-benessere', 'Massaggiatore', 'massaggiatore', 12),
  ('salute-benessere', 'Tatuatore', 'tatuatore-salute', 13),
  ('salute-benessere', 'Ospedale', 'ospedale-salute', 14),
  ('salute-benessere', 'Clinica', 'clinica-salute', 15),
  ('salute-benessere', 'Centro sportivo', 'centro-sportivo-salute', 16),
  ('salute-benessere', 'Palestra', 'palestra', 17),
  ('salute-benessere', 'Yoga', 'yoga', 18),
  ('salute-benessere', 'Piscina', 'piscina', 19),
  ('salute-benessere', 'Sauna', 'sauna-salute', 20),
  ('trasporti', 'Autosoccorso', 'autosoccorso', 0),
  ('trasporti', 'Noleggio auto', 'noleggio-auto', 1),
  ('trasporti', 'Noleggio furgoni', 'noleggio-furgoni', 2),
  ('trasporti', 'Noleggio biciclette', 'noleggio-biciclette-trasp', 3),
  ('trasporti', 'Taxi', 'taxi', 4),
  ('trasporti', 'Autista', 'autista', 5),
  ('trasporti', 'Traslochi', 'traslochi', 6),
  ('trasporti', 'Logistica', 'logistica', 7),
  ('trasporti', 'Corrieri', 'corrieri', 8),
  ('trasporti', 'Parcheggio', 'parcheggio-trasp', 9),
  ('trasporti', 'Colonnine ricarica', 'colonnine-ricarica-trasp', 10),
  ('trasporti', 'Stazione servizio', 'stazione-servizio', 11),
  ('trasporti', 'Officina auto', 'officina-auto', 12),
  ('trasporti', 'Gommista', 'gommista', 13),
  ('trasporti', 'Carrozzeria', 'carrozzeria', 14),
  ('trasporti', 'Aree Camper', 'aree-camper-trasp', 15),
  ('istruzione', 'Scuola infanzia', 'scuola-infanzia', 0),
  ('istruzione', 'Scuola primaria', 'scuola-primaria', 1),
  ('istruzione', 'Scuola secondaria', 'scuola-secondaria', 2),
  ('istruzione', 'Universita', 'universita', 3),
  ('istruzione', 'Formazione professionale', 'formazione-professionale', 4),
  ('istruzione', 'Corsi lingue', 'corsi-lingue', 5),
  ('istruzione', 'Ripetizioni private', 'ripetizioni-private', 6),
  ('istruzione', 'Musica', 'musica-istruzione', 7),
  ('istruzione', 'Arte', 'arte-istruzione', 8),
  ('istruzione', 'Corsi informatica', 'corsi-informatica', 9),
  ('istruzione', 'Biblioteca', 'biblioteca-istruzione', 10),
  ('istruzione', 'Asilo nido', 'asilo-nido', 11),
  ('agricoltura', 'Azienda agricola', 'azienda-agricola', 0),
  ('agricoltura', 'Allevamento', 'allevamento', 1),
  ('agricoltura', 'Viticoltura', 'viticoltura', 2),
  ('agricoltura', 'Olivicoltura', 'olivicoltura', 3),
  ('agricoltura', 'Frutticoltura', 'frutticoltura', 4),
  ('agricoltura', 'Orticoltura', 'orticoltura', 5),
  ('agricoltura', 'Apicoltura', 'apicoltura', 6),
  ('agricoltura', 'Agriturismo', 'agriturismo-agri', 7),
  ('agricoltura', 'Vendita diretta', 'vendita-diretta', 8),
  ('agricoltura', 'Sementi', 'sementi', 9),
  ('industria', 'Metalmeccanica', 'metalmeccanica', 0),
  ('industria', 'Fonderia', 'fonderia', 1),
  ('industria', 'Lavorazione metalli', 'lavorazione-metalli', 2),
  ('industria', 'Industria alimentare', 'industria-alimentare', 3),
  ('industria', 'Industria tessile', 'industria-tessile', 4),
  ('industria', 'Industria chimica', 'industria-chimica', 5),
  ('industria', 'Industria del legno', 'industria-legno', 6),
  ('industria', 'Industria della carta', 'industria-carta', 7),
  ('industria', 'Stampa', 'stampa', 8),
  ('industria', 'Confezioni', 'confezioni', 9),
  ('industria', 'Energia', 'energia-industria', 10),
  ('industria', 'Impianti elettrici', 'impianti-elettrici', 11)
) AS mc(macro_slug, name, slug, sort_order)
ON cmc.slug = mc.macro_slug
ON CONFLICT DO NOTHING;
