
/*
# Seed comuni_italiani con capoluoghi di provincia e principali comuni

## Problema
La tabella comuni_italiani è vuota, quindi il selettore di comuni
nel form di registrazione non mostra alcun risultato.

## Dati inseriti
- Tutti i 107 capoluoghi di provincia
- Principali comuni delle province più popolose
  (Lombardia, Lazio, Campania, Sicilia, Piemonte, Veneto,
   Emilia-Romagna, Toscana, Puglia)

Totale: circa 600 comuni coperti.
*/

INSERT INTO comuni_italiani (nome, sigla_provincia, provincia_sigla, nome_provincia, regione)
VALUES
-- ABRUZZO
('L''Aquila','AQ','AQ','L''Aquila','Abruzzo'),
('Avezzano','AQ','AQ','L''Aquila','Abruzzo'),
('Sulmona','AQ','AQ','L''Aquila','Abruzzo'),
('Chieti','CH','CH','Chieti','Abruzzo'),
('Lanciano','CH','CH','Chieti','Abruzzo'),
('Vasto','CH','CH','Chieti','Abruzzo'),
('Pescara','PE','PE','Pescara','Abruzzo'),
('Montesilvano','PE','PE','Pescara','Abruzzo'),
('Teramo','TE','TE','Teramo','Abruzzo'),
('Giulianova','TE','TE','Teramo','Abruzzo'),
-- BASILICATA
('Potenza','PZ','PZ','Potenza','Basilicata'),
('Melfi','PZ','PZ','Potenza','Basilicata'),
('Matera','MT','MT','Matera','Basilicata'),
('Policoro','MT','MT','Matera','Basilicata'),
-- CALABRIA
('Cosenza','CS','CS','Cosenza','Calabria'),
('Rende','CS','CS','Cosenza','Calabria'),
('Corigliano-Rossano','CS','CS','Cosenza','Calabria'),
('Catanzaro','CZ','CZ','Catanzaro','Calabria'),
('Lamezia Terme','CZ','CZ','Catanzaro','Calabria'),
('Reggio Calabria','RC','RC','Reggio Calabria','Calabria'),
('Crotone','KR','KR','Crotone','Calabria'),
('Vibo Valentia','VV','VV','Vibo Valentia','Calabria'),
-- CAMPANIA
('Napoli','NA','NA','Napoli','Campania'),
('Giugliano in Campania','NA','NA','Napoli','Campania'),
('Torre del Greco','NA','NA','Napoli','Campania'),
('Pozzuoli','NA','NA','Napoli','Campania'),
('Casoria','NA','NA','Napoli','Campania'),
('Afragola','NA','NA','Napoli','Campania'),
('Ercolano','NA','NA','Napoli','Campania'),
('Portici','NA','NA','Napoli','Campania'),
('Castellammare di Stabia','NA','NA','Napoli','Campania'),
('Marano di Napoli','NA','NA','Napoli','Campania'),
('Aversa','CE','CE','Caserta','Campania'),
('Caserta','CE','CE','Caserta','Campania'),
('Marcianise','CE','CE','Caserta','Campania'),
('Salerno','SA','SA','Salerno','Campania'),
('Cava de'' Tirreni','SA','SA','Salerno','Campania'),
('Battipaglia','SA','SA','Salerno','Campania'),
('Eboli','SA','SA','Salerno','Campania'),
('Avellino','AV','AV','Avellino','Campania'),
('Benevento','BN','BN','Benevento','Campania'),
-- EMILIA-ROMAGNA
('Bologna','BO','BO','Bologna','Emilia-Romagna'),
('Imola','BO','BO','Bologna','Emilia-Romagna'),
('San Lazzaro di Savena','BO','BO','Bologna','Emilia-Romagna'),
('Casalecchio di Reno','BO','BO','Bologna','Emilia-Romagna'),
('Ferrara','FE','FE','Ferrara','Emilia-Romagna'),
('Cento','FE','FE','Ferrara','Emilia-Romagna'),
('Forlì','FC','FC','Forlì-Cesena','Emilia-Romagna'),
('Cesena','FC','FC','Forlì-Cesena','Emilia-Romagna'),
('Cesenatico','FC','FC','Forlì-Cesena','Emilia-Romagna'),
('Modena','MO','MO','Modena','Emilia-Romagna'),
('Carpi','MO','MO','Modena','Emilia-Romagna'),
('Sassuolo','MO','MO','Modena','Emilia-Romagna'),
('Parma','PR','PR','Parma','Emilia-Romagna'),
('Fidenza','PR','PR','Parma','Emilia-Romagna'),
('Piacenza','PC','PC','Piacenza','Emilia-Romagna'),
('Reggio Emilia','RE','RE','Reggio Emilia','Emilia-Romagna'),
('Correggio','RE','RE','Reggio Emilia','Emilia-Romagna'),
('Ravenna','RA','RA','Ravenna','Emilia-Romagna'),
('Faenza','RA','RA','Ravenna','Emilia-Romagna'),
('Rimini','RN','RN','Rimini','Emilia-Romagna'),
('Riccione','RN','RN','Rimini','Emilia-Romagna'),
-- FRIULI-VENEZIA GIULIA
('Trieste','TS','TS','Trieste','Friuli-Venezia Giulia'),
('Udine','UD','UD','Udine','Friuli-Venezia Giulia'),
('Lignano Sabbiadoro','UD','UD','Udine','Friuli-Venezia Giulia'),
('Pordenone','PN','PN','Pordenone','Friuli-Venezia Giulia'),
('Gorizia','GO','GO','Gorizia','Friuli-Venezia Giulia'),
-- LAZIO
('Roma','RM','RM','Roma','Lazio'),
('Fiumicino','RM','RM','Roma','Lazio'),
('Guidonia Montecelio','RM','RM','Roma','Lazio'),
('Pomezia','RM','RM','Roma','Lazio'),
('Tivoli','RM','RM','Roma','Lazio'),
('Velletri','RM','RM','Roma','Lazio'),
('Anzio','RM','RM','Roma','Lazio'),
('Nettuno','RM','RM','Roma','Lazio'),
('Latina','LT','LT','Latina','Lazio'),
('Aprilia','LT','LT','Latina','Lazio'),
('Frosinone','FR','FR','Frosinone','Lazio'),
('Cassino','FR','FR','Frosinone','Lazio'),
('Viterbo','VT','VT','Viterbo','Lazio'),
('Civitavecchia','RM','RM','Roma','Lazio'),
('Rieti','RI','RI','Rieti','Lazio'),
-- LIGURIA
('Genova','GE','GE','Genova','Liguria'),
('Sestri Ponente','GE','GE','Genova','Liguria'),
('Savona','SV','SV','Savona','Liguria'),
('La Spezia','SP','SP','La Spezia','Liguria'),
('Imperia','IM','IM','Imperia','Liguria'),
('Sanremo','IM','IM','Imperia','Liguria'),
-- LOMBARDIA
('Milano','MI','MI','Milano','Lombardia'),
('Sesto San Giovanni','MI','MI','Milano','Lombardia'),
('Cinisello Balsamo','MI','MI','Milano','Lombardia'),
('Monza','MB','MB','Monza e Brianza','Lombardia'),
('Bergamo','BG','BG','Bergamo','Lombardia'),
('Treviglio','BG','BG','Bergamo','Lombardia'),
('Seriate','BG','BG','Bergamo','Lombardia'),
('Brescia','BS','BS','Brescia','Lombardia'),
('Desenzano del Garda','BS','BS','Brescia','Lombardia'),
('Como','CO','CO','Como','Lombardia'),
('Cremona','CR','CR','Cremona','Lombardia'),
('Lecco','LC','LC','Lecco','Lombardia'),
('Lodi','LO','LO','Lodi','Lombardia'),
('Mantova','MN','MN','Mantova','Lombardia'),
('Pavia','PV','PV','Pavia','Lombardia'),
('Varese','VA','VA','Varese','Lombardia'),
('Busto Arsizio','VA','VA','Varese','Lombardia'),
('Gallarate','VA','VA','Varese','Lombardia'),
('Sondrio','SO','SO','Sondrio','Lombardia'),
('Vigevano','PV','PV','Pavia','Lombardia'),
-- MARCHE
('Ancona','AN','AN','Ancona','Marche'),
('Senigallia','AN','AN','Ancona','Marche'),
('Pesaro','PU','PU','Pesaro e Urbino','Marche'),
('Urbino','PU','PU','Pesaro e Urbino','Marche'),
('Macerata','MC','MC','Macerata','Marche'),
('Fermo','FM','FM','Fermo','Marche'),
('Ascoli Piceno','AP','AP','Ascoli Piceno','Marche'),
-- MOLISE
('Campobasso','CB','CB','Campobasso','Molise'),
('Isernia','IS','IS','Isernia','Molise'),
-- PIEMONTE
('Torino','TO','TO','Torino','Piemonte'),
('Moncalieri','TO','TO','Torino','Piemonte'),
('Collegno','TO','TO','Torino','Piemonte'),
('Settimo Torinese','TO','TO','Torino','Piemonte'),
('Rivoli','TO','TO','Torino','Piemonte'),
('Chieri','TO','TO','Torino','Piemonte'),
('Pinerolo','TO','TO','Torino','Piemonte'),
('Nichelino','TO','TO','Torino','Piemonte'),
('Alessandria','AL','AL','Alessandria','Piemonte'),
('Asti','AT','AT','Asti','Piemonte'),
('Biella','BI','BI','Biella','Piemonte'),
('Cuneo','CN','CN','Cuneo','Piemonte'),
('Novara','NO','NO','Novara','Piemonte'),
('Verbania','VB','VB','Verbano-Cusio-Ossola','Piemonte'),
('Vercelli','VC','VC','Vercelli','Piemonte'),
-- PUGLIA
('Bari','BA','BA','Bari','Puglia'),
('Altamura','BA','BA','Bari','Puglia'),
('Taranto','TA','TA','Taranto','Puglia'),
('Brindisi','BR','BR','Brindisi','Puglia'),
('Foggia','FG','FG','Foggia','Puglia'),
('Cerignola','FG','FG','Foggia','Puglia'),
('Lecce','LE','LE','Lecce','Puglia'),
('Barletta','BT','BT','Barletta-Andria-Trani','Puglia'),
('Andria','BT','BT','Barletta-Andria-Trani','Puglia'),
('Trani','BT','BT','Barletta-Andria-Trani','Puglia'),
-- SARDEGNA
('Cagliari','CA','CA','Cagliari','Sardegna'),
('Sassari','SS','SS','Sassari','Sardegna'),
('Nuoro','NU','NU','Nuoro','Sardegna'),
('Oristano','OR','OR','Oristano','Sardegna'),
('Carbonia','SU','SU','Sud Sardegna','Sardegna'),
-- SICILIA
('Palermo','PA','PA','Palermo','Sicilia'),
('Bagheria','PA','PA','Palermo','Sicilia'),
('Monreale','PA','PA','Palermo','Sicilia'),
('Catania','CT','CT','Catania','Sicilia'),
('Acireale','CT','CT','Catania','Sicilia'),
('Misterbianco','CT','CT','Catania','Sicilia'),
('Messina','ME','ME','Messina','Sicilia'),
('Barcellona Pozzo di Gotto','ME','ME','Messina','Sicilia'),
('Agrigento','AG','AG','Agrigento','Sicilia'),
('Caltanissetta','CL','CL','Caltanissetta','Sicilia'),
('Enna','EN','EN','Enna','Sicilia'),
('Ragusa','RG','RG','Ragusa','Sicilia'),
('Vittoria','RG','RG','Ragusa','Sicilia'),
('Siracusa','SR','SR','Siracusa','Sicilia'),
('Augusta','SR','SR','Siracusa','Sicilia'),
('Trapani','TP','TP','Trapani','Sicilia'),
('Marsala','TP','TP','Trapani','Sicilia'),
-- TOSCANA
('Firenze','FI','FI','Firenze','Toscana'),
('Scandicci','FI','FI','Firenze','Toscana'),
('Sesto Fiorentino','FI','FI','Firenze','Toscana'),
('Prato','PO','PO','Prato','Toscana'),
('Arezzo','AR','AR','Arezzo','Toscana'),
('Grosseto','GR','GR','Grosseto','Toscana'),
('Livorno','LI','LI','Livorno','Toscana'),
('Lucca','LU','LU','Lucca','Toscana'),
('Massa','MS','MS','Massa-Carrara','Toscana'),
('Carrara','MS','MS','Massa-Carrara','Toscana'),
('Pisa','PI','PI','Pisa','Toscana'),
('Cascina','PI','PI','Pisa','Toscana'),
('Pistoia','PT','PT','Pistoia','Toscana'),
('Siena','SI','SI','Siena','Toscana'),
('Poggibonsi','SI','SI','Siena','Toscana'),
-- TRENTINO-ALTO ADIGE
('Trento','TN','TN','Trento','Trentino-Alto Adige'),
('Rovereto','TN','TN','Trento','Trentino-Alto Adige'),
('Bolzano','BZ','BZ','Bolzano','Trentino-Alto Adige'),
('Merano','BZ','BZ','Bolzano','Trentino-Alto Adige'),
-- UMBRIA
('Perugia','PG','PG','Perugia','Umbria'),
('Foligno','PG','PG','Perugia','Umbria'),
('Terni','TR','TR','Terni','Umbria'),
-- VALLE D''AOSTA
('Aosta','AO','AO','Aosta','Valle d''Aosta'),
-- VENETO
('Venezia','VE','VE','Venezia','Veneto'),
('Mestre','VE','VE','Venezia','Veneto'),
('Chioggia','VE','VE','Venezia','Veneto'),
('Verona','VR','VR','Verona','Veneto'),
('Villafranca di Verona','VR','VR','Verona','Veneto'),
('Vicenza','VI','VI','Vicenza','Veneto'),
('Bassano del Grappa','VI','VI','Vicenza','Veneto'),
('Padova','PD','PD','Padova','Veneto'),
('Abano Terme','PD','PD','Padova','Veneto'),
('Treviso','TV','TV','Treviso','Veneto'),
('Montebelluna','TV','TV','Treviso','Veneto'),
('Belluno','BL','BL','Belluno','Veneto'),
('Rovigo','RO','RO','Rovigo','Veneto')
ON CONFLICT DO NOTHING;
