-- Add missing business categories needed for OSM import (with slug)
INSERT INTO business_categories (name, slug) VALUES
  ('Farmacia', 'farmacia'),
  ('Ottico', 'ottico'),
  ('Ospedale', 'ospedale'),
  ('Clinica', 'clinica'),
  ('Fisioterapista', 'fisioterapista'),
  ('Laboratorio analisi', 'laboratorio-analisi'),
  ('Parrucchiere', 'parrucchiere'),
  ('Estetista', 'estetista'),
  ('Massaggiatore', 'massaggiatore'),
  ('Tatuatore', 'tatuatore'),
  ('Motel', 'motel'),
  ('Ostello', 'ostello'),
  ('Aree Camper', 'aree-camper'),
  ('Chalet', 'chalet'),
  ('Banca', 'banca'),
  ('Bancomat', 'bancomat'),
  ('Assicurazione', 'assicurazione'),
  ('Notaio', 'notaio'),
  ('Consulente finanziario', 'consulente-finanziario'),
  ('Consulente fiscale', 'consulente-fiscale'),
  ('Architetto', 'architetto'),
  ('Ingegnere', 'ingegnere'),
  ('Agenzia del lavoro', 'agenzia-del-lavoro'),
  ('Consulenza', 'consulenza'),
  ('Scuola', 'scuola'),
  ('Asilo nido', 'asilo-nido'),
  ('Scuola lingue', 'scuola-lingue'),
  ('Scuola danza', 'scuola-danza'),
  ('Sartoria', 'sartoria'),
  ('Elettronica', 'elettronica'),
  ('Telefonia', 'telefonia'),
  ('Illuminazione', 'illuminazione'),
  ('Libreria', 'libreria'),
  ('Cartoleria', 'cartoleria'),
  ('Fiorista', 'fiorista'),
  ('Gioielleria', 'gioielleria'),
  ('Orologeria', 'orologeria'),
  ('Giocattoli', 'giocattoli'),
  ('Negozio animali', 'negozio-animali'),
  ('Toelettatura', 'toelettatura'),
  ('Ferramenta', 'ferramenta'),
  ('Colorificio', 'colorificio'),
  ('Officina meccanica', 'officina-meccanica'),
  ('Noleggio auto', 'noleggio-auto'),
  ('Concessionaria', 'concessionaria'),
  ('Gommista', 'gommista'),
  ('Centro revisioni', 'centro-revisioni'),
  ('Centro sportivo', 'centro-sportivo'),
  ('Piscina', 'piscina'),
  ('Arti marziali', 'arti-marziali'),
  ('Ufficio postale', 'ufficio-postale'),
  ('Onoranze funebri', 'onoranze-funebri'),
  ('Tipografia', 'tipografia'),
  ('Fabbro', 'fabbro'),
  ('Falegname', 'falegname'),
  ('Idraulico', 'idraulico'),
  ('Elettricista', 'elettricista'),
  ('Imbianchino', 'imbianchino'),
  ('Calzolaio', 'calzolaio'),
  ('Duplicazione chiavi', 'duplicazione-chiavi'),
  ('Lattoniere', 'lattoniere'),
  ('Apicoltura', 'apicoltura'),
  ('Cantina', 'cantina'),
  ('Distilleria', 'distilleria'),
  ('Biblioteca', 'biblioteca'),
  ('Colonnine ricarica', 'colonnine-ricarica'),
  ('Parcheggio', 'parcheggio'),
  ('Noleggio biciclette', 'noleggio-biciclette'),
  ('Discoteca', 'discoteca'),
  ('Sauna', 'sauna'),
  ('Torrefazione', 'torrefazione'),
  ('Macelleria', 'macelleria'),
  ('Pescheria', 'pescheria'),
  ('Gastronomia', 'gastronomia'),
  ('Latteria', 'latteria'),
  ('Panificio', 'panificio'),
  ('Pasticceria', 'pasticceria'),
  ('Pizzeria', 'pizzeria'),
  ('Ristorante', 'ristorante'),
  ('Street Food', 'street-food'),
  ('Pub', 'pub'),
  ('Gelateria', 'gelateria'),
  ('Catering', 'catering'),
  ('Ristorazione', 'ristorazione'),
  ('Produzione alimentare', 'produzione-alimentare'),
  ('Turismo', 'turismo'),
  ('Villaggio turistico', 'villaggio-turistico'),
  ('Resort', 'resort'),
  ('Casa vacanze', 'casa-vacanze'),
  ('Agriturismo', 'agriturismo')
ON CONFLICT (name) DO NOTHING;
