/*
# Create guess_category_id helper function

Creates a keyword-matching function that maps a business name/description
to a category_id. Used by the next migration to assign categories to
~146K unclaimed businesses and ~11.6K old businesses that lost their
category_id when categories were replaced in migration 20260705202618.
*/

CREATE OR REPLACE FUNCTION public.guess_category_id(search_text text)
RETURNS uuid
LANGUAGE plpgsql
IMMUTABLE
AS $$
DECLARE
  t text := LOWER(search_text);
  cat_id uuid;
BEGIN
  cat_id := CASE
    -- Ristorazione
    WHEN t LIKE '%pizzer%' THEN (SELECT id FROM business_categories WHERE name = 'Pizzeria' LIMIT 1)
    WHEN t LIKE '%gelat%' THEN (SELECT id FROM business_categories WHERE name = 'Gelateria' LIMIT 1)
    WHEN t LIKE '%pasticer%' THEN (SELECT id FROM business_categories WHERE name = 'Pasticceria' LIMIT 1)
    WHEN t LIKE '%panif%' OR t LIKE '%panet%eri%' THEN (SELECT id FROM business_categories WHERE name = 'Panificio' LIMIT 1)
    WHEN t LIKE '%gastronom%' THEN (SELECT id FROM business_categories WHERE name = 'Gastronomia' LIMIT 1)
    WHEN t LIKE '%street food%' OR t LIKE '%fast food%' THEN (SELECT id FROM business_categories WHERE name = 'Street Food' LIMIT 1)
    WHEN t LIKE '%catering%' THEN (SELECT id FROM business_categories WHERE name = 'Catering' LIMIT 1)
    WHEN t LIKE '%pub%' OR t LIKE '%biergarten%' OR t LIKE '%birreri%' THEN (SELECT id FROM business_categories WHERE name = 'Pub' LIMIT 1)
    WHEN t LIKE '%bar%' OR t LIKE '%caff%' OR t LIKE '%coffee%' THEN (SELECT id FROM business_categories WHERE name = 'Bar' LIMIT 1)
    WHEN t LIKE '%ristor%' OR t LIKE '%trattor%' OR t LIKE '%oster%' OR t LIKE '%cucina%' THEN (SELECT id FROM business_categories WHERE name = 'Ristorante' LIMIT 1)
    -- Turismo
    WHEN t LIKE '%hotel%' OR t LIKE '%albergo%' THEN (SELECT id FROM business_categories WHERE name = 'Hotel' LIMIT 1)
    WHEN t LIKE '%b&b%' OR t LIKE '%bed and breakfast%' OR t LIKE '%bed & breakfast%' THEN (SELECT id FROM business_categories WHERE name = 'B&B' LIMIT 1)
    WHEN t LIKE '%agrituris%' THEN (SELECT id FROM business_categories WHERE name = 'Agriturismo' LIMIT 1)
    WHEN t LIKE '%campegg%' OR t LIKE '%camping%' THEN (SELECT id FROM business_categories WHERE name = 'Campeggio' LIMIT 1)
    WHEN t LIKE '%resort%' THEN (SELECT id FROM business_categories WHERE name = 'Resort' LIMIT 1)
    WHEN t LIKE '%villaggio%' THEN (SELECT id FROM business_categories WHERE name = 'Villaggio turistico' LIMIT 1)
    WHEN t LIKE '%ostello%' OR t LIKE '%hostel%' THEN (SELECT id FROM business_categories WHERE name = 'Ostello' LIMIT 1)
    WHEN t LIKE '%agenzia viaggi%' OR t LIKE '%travel agency%' THEN (SELECT id FROM business_categories WHERE name = 'Agenzia viaggi' LIMIT 1)
    WHEN t LIKE '%guida turistic%' THEN (SELECT id FROM business_categories WHERE name = 'Guida turistica' LIMIT 1)
    -- Artigiani
    WHEN t LIKE '%falegnam%' THEN (SELECT id FROM business_categories WHERE name = 'Falegname' LIMIT 1)
    WHEN t LIKE '%idraulic%' THEN (SELECT id FROM business_categories WHERE name = 'Idraulico' LIMIT 1)
    WHEN t LIKE '%termoidraulic%' THEN (SELECT id FROM business_categories WHERE name = 'Termoidraulico' LIMIT 1)
    WHEN t LIKE '%elettricist%' OR t LIKE '%impianti elettric%' THEN (SELECT id FROM business_categories WHERE name = 'Elettricista' LIMIT 1)
    WHEN t LIKE '%murator%' THEN (SELECT id FROM business_categories WHERE name = 'Muratore' LIMIT 1)
    WHEN t LIKE '%piastrellist%' THEN (SELECT id FROM business_categories WHERE name = 'Piastrellista' LIMIT 1)
    WHEN t LIKE '%imbianchin%' OR t LIKE '%tinteggi%' THEN (SELECT id FROM business_categories WHERE name = 'Imbianchino' LIMIT 1)
    WHEN t LIKE '%cartongess%' THEN (SELECT id FROM business_categories WHERE name = 'Cartongessista' LIMIT 1)
    WHEN t LIKE '%fabbro%' THEN (SELECT id FROM business_categories WHERE name = 'Fabbro' LIMIT 1)
    WHEN t LIKE '%serrament%' OR t LIKE '%infiss%' THEN (SELECT id FROM business_categories WHERE name = 'Serramentista' LIMIT 1)
    WHEN t LIKE '%tetto%' THEN (SELECT id FROM business_categories WHERE name = 'Tettoista' LIMIT 1)
    WHEN t LIKE '%lattonier%' THEN (SELECT id FROM business_categories WHERE name = 'Lattoniere' LIMIT 1)
    WHEN t LIKE '%paviment%' THEN (SELECT id FROM business_categories WHERE name = 'Pavimentista' LIMIT 1)
    WHEN t LIKE '%parquet%' THEN (SELECT id FROM business_categories WHERE name = 'Parquettista' LIMIT 1)
    WHEN t LIKE '%giardiniere%' OR t LIKE '%giardinaggio%' THEN (SELECT id FROM business_categories WHERE name = 'Giardiniere' LIMIT 1)
    WHEN t LIKE '%potator%' THEN (SELECT id FROM business_categories WHERE name = 'Potatore' LIMIT 1)
    WHEN t LIKE '%antennist%' THEN (SELECT id FROM business_categories WHERE name = 'Antennista' LIMIT 1)
    WHEN t LIKE '%climatizz%' OR t LIKE '%condizion%' THEN (SELECT id FROM business_categories WHERE name = 'Tecnico climatizzatori' LIMIT 1)
    WHEN t LIKE '%fotovoltaic%' THEN (SELECT id FROM business_categories WHERE name = 'Installatore fotovoltaico' LIMIT 1)
    -- Edilizia
    WHEN t LIKE '%impresa edil%' OR t LIKE '%costruzion%' THEN (SELECT id FROM business_categories WHERE name = 'Impresa edile' LIMIT 1)
    WHEN t LIKE '%ristrutture%' THEN (SELECT id FROM business_categories WHERE name = 'Ristrutturazioni' LIMIT 1)
    WHEN t LIKE '%demoliz%' THEN (SELECT id FROM business_categories WHERE name = 'Demolizioni' LIMIT 1)
    WHEN t LIKE '%scav%' THEN (SELECT id FROM business_categories WHERE name = 'Scavi' LIMIT 1)
    WHEN t LIKE '%pontegg%' THEN (SELECT id FROM business_categories WHERE name = 'Ponteggi' LIMIT 1)
    WHEN t LIKE '%impermeabil%' THEN (SELECT id FROM business_categories WHERE name = 'Impermeabilizzazioni' LIMIT 1)
    WHEN t LIKE '%restauro%' THEN (SELECT id FROM business_categories WHERE name = 'Restauro edifici' LIMIT 1)
    -- Casa e Servizi
    WHEN t LIKE '%puliz%' OR t LIKE '%cleaning%' THEN (SELECT id FROM business_categories WHERE name = 'Impresa di pulizie' LIMIT 1)
    WHEN t LIKE '%disinfest%' THEN (SELECT id FROM business_categories WHERE name = 'Disinfestazione' LIMIT 1)
    WHEN t LIKE '%spurghi%' THEN (SELECT id FROM business_categories WHERE name = 'Spurghi' LIMIT 1)
    WHEN t LIKE '%traslochi%' OR t LIKE '%trasloc%' THEN (SELECT id FROM business_categories WHERE name = 'Traslochi' LIMIT 1)
    WHEN t LIKE '%sgomber%' THEN (SELECT id FROM business_categories WHERE name = 'Sgomberi' LIMIT 1)
    WHEN t LIKE '%lavander%' OR t LIKE '%lavasec%' THEN (SELECT id FROM business_categories WHERE name = 'Lavanderia' LIMIT 1)
    WHEN t LIKE '%sartor%' OR t LIKE '%sarti%' THEN (SELECT id FROM business_categories WHERE name = 'Sartoria' LIMIT 1)
    WHEN t LIKE '%calzola%' THEN (SELECT id FROM business_categories WHERE name = 'Calzolaio' LIMIT 1)
    WHEN t LIKE '%duplicaz%chiav%' THEN (SELECT id FROM business_categories WHERE name = 'Duplicazione chiavi' LIMIT 1)
    -- Automotive
    WHEN t LIKE '%autofficin%' OR t LIKE '%officin%meccanic%' THEN (SELECT id FROM business_categories WHERE name = 'Officina meccanica' LIMIT 1)
    WHEN t LIKE '%carrozzer%' THEN (SELECT id FROM business_categories WHERE name = 'Carrozzeria' LIMIT 1)
    WHEN t LIKE '%gommist%' OR t LIKE '%pneumatic%' THEN (SELECT id FROM business_categories WHERE name = 'Gommista' LIMIT 1)
    WHEN t LIKE '%elettraut%' THEN (SELECT id FROM business_categories WHERE name = 'Elettrauto' LIMIT 1)
    WHEN t LIKE '%revision%auto%' OR t LIKE '%centro revision%' THEN (SELECT id FROM business_categories WHERE name = 'Centro revisioni' LIMIT 1)
    WHEN t LIKE '%soccorso strad%' THEN (SELECT id FROM business_categories WHERE name = 'Soccorso stradale' LIMIT 1)
    WHEN t LIKE '%autolavagg%' OR t LIKE '%car wash%' THEN (SELECT id FROM business_categories WHERE name = 'Autolavaggio' LIMIT 1)
    WHEN t LIKE '%autonolegg%' OR t LIKE '%nolegg%auto%' OR t LIKE '%rent a car%' THEN (SELECT id FROM business_categories WHERE name = 'Noleggio auto' LIMIT 1)
    WHEN t LIKE '%nolegg%furgon%' THEN (SELECT id FROM business_categories WHERE name = 'Noleggio furgoni' LIMIT 1)
    WHEN t LIKE '%concessionar%' THEN (SELECT id FROM business_categories WHERE name = 'Concessionaria' LIMIT 1)
    WHEN t LIKE '%autoscuol%' THEN (SELECT id FROM business_categories WHERE name = 'Autoscuola' LIMIT 1)
    -- Fuel stations
    WHEN t ~ '^(esso|agip|q8|total|eni|erg|ip|repsol|tamoil|shell|api|futura)' THEN (SELECT id FROM business_categories WHERE name = 'Gommista' LIMIT 1)
    -- Studi Professionali
    WHEN t LIKE '%avvocat%' THEN (SELECT id FROM business_categories WHERE name = 'Avvocato' LIMIT 1)
    WHEN t LIKE '%notai%' THEN (SELECT id FROM business_categories WHERE name = 'Notaio' LIMIT 1)
    WHEN t LIKE '%commercialist%' THEN (SELECT id FROM business_categories WHERE name = 'Commercialista' LIMIT 1)
    WHEN t LIKE '%consulente del lavoro%' THEN (SELECT id FROM business_categories WHERE name = 'Consulente del lavoro' LIMIT 1)
    WHEN t LIKE '%tributarist%' THEN (SELECT id FROM business_categories WHERE name = 'Tributarista' LIMIT 1)
    -- Salute
    WHEN t LIKE '%dentist%' OR t LIKE '%odontoiatr%' THEN (SELECT id FROM business_categories WHERE name = 'Dentista' LIMIT 1)
    WHEN t LIKE '%ortodont%' THEN (SELECT id FROM business_categories WHERE name = 'Ortodontista' LIMIT 1)
    WHEN t LIKE '%medico%' OR t LIKE '%studio medic%' THEN (SELECT id FROM business_categories WHERE name = 'Medico di base' LIMIT 1)
    WHEN t LIKE '%cardiolog%' THEN (SELECT id FROM business_categories WHERE name = 'Cardiologo' LIMIT 1)
    WHEN t LIKE '%dermatolog%' THEN (SELECT id FROM business_categories WHERE name = 'Dermatologo' LIMIT 1)
    WHEN t LIKE '%ortoped%' THEN (SELECT id FROM business_categories WHERE name = 'Ortopedico' LIMIT 1)
    WHEN t LIKE '%neurolog%' THEN (SELECT id FROM business_categories WHERE name = 'Neurologo' LIMIT 1)
    WHEN t LIKE '%pediatr%' THEN (SELECT id FROM business_categories WHERE name = 'Pediatra' LIMIT 1)
    WHEN t LIKE '%ginecolog%' THEN (SELECT id FROM business_categories WHERE name = 'Ginecologo' LIMIT 1)
    WHEN t LIKE '%oculist%' THEN (SELECT id FROM business_categories WHERE name = 'Oculista' LIMIT 1)
    WHEN t LIKE '%psicolog%' THEN (SELECT id FROM business_categories WHERE name = 'Psicologo' LIMIT 1)
    WHEN t LIKE '%psicoterap%' THEN (SELECT id FROM business_categories WHERE name = 'Psicoterapeuta' LIMIT 1)
    WHEN t LIKE '%psichiatr%' THEN (SELECT id FROM business_categories WHERE name = 'Psichiatra' LIMIT 1)
    WHEN t LIKE '%fisioterap%' THEN (SELECT id FROM business_categories WHERE name = 'Fisioterapista' LIMIT 1)
    WHEN t LIKE '%osteopat%' THEN (SELECT id FROM business_categories WHERE name = 'Osteopata' LIMIT 1)
    WHEN t LIKE '%chiroprat%' THEN (SELECT id FROM business_categories WHERE name = 'Chiropratico' LIMIT 1)
    WHEN t LIKE '%nutrizionist%' THEN (SELECT id FROM business_categories WHERE name = 'Nutrizionista' LIMIT 1)
    WHEN t LIKE '%dietist%' THEN (SELECT id FROM business_categories WHERE name = 'Dietista' LIMIT 1)
    WHEN t LIKE '%infermier%' THEN (SELECT id FROM business_categories WHERE name = 'Infermiere' LIMIT 1)
    WHEN t LIKE '%ostetric%' THEN (SELECT id FROM business_categories WHERE name = 'Ostetrica' LIMIT 1)
    WHEN t LIKE '%logoped%' THEN (SELECT id FROM business_categories WHERE name = 'Logopedista' LIMIT 1)
    WHEN t LIKE '%podolog%' THEN (SELECT id FROM business_categories WHERE name = 'Podologo' LIMIT 1)
    WHEN t LIKE '%veterinar%' THEN (SELECT id FROM business_categories WHERE name = 'Veterinario' LIMIT 1)
    WHEN t LIKE '%farmac%' THEN (SELECT id FROM business_categories WHERE name = 'Alimentari' LIMIT 1)
    WHEN t LIKE '%clinic%' OR t LIKE '%ospedal%' THEN (SELECT id FROM business_categories WHERE name = 'Medico di base' LIMIT 1)
    -- Benessere
    WHEN t LIKE '%parrucch%' OR t LIKE '%hairdress%' OR t LIKE '%salon%' THEN (SELECT id FROM business_categories WHERE name = 'Parrucchiere' LIMIT 1)
    WHEN t LIKE '%barbier%' THEN (SELECT id FROM business_categories WHERE name = 'Barbiere' LIMIT 1)
    WHEN t LIKE '%estetist%' OR t LIKE '%centro estetic%' THEN (SELECT id FROM business_categories WHERE name = 'Estetista' LIMIT 1)
    WHEN t LIKE '%nail%' OR t LIKE '%unghie%' THEN (SELECT id FROM business_categories WHERE name = 'Nail Artist' LIMIT 1)
    WHEN t LIKE '%make%up%' OR t LIKE '%trucco%' THEN (SELECT id FROM business_categories WHERE name = 'Make-up Artist' LIMIT 1)
    WHEN t LIKE '%massagg%' THEN (SELECT id FROM business_categories WHERE name = 'Massaggiatore' LIMIT 1)
    WHEN t LIKE '%tattoo%' OR t LIKE '%tatuagg%' THEN (SELECT id FROM business_categories WHERE name = 'Tattoo Artist' LIMIT 1)
    WHEN t LIKE '%pierc%' THEN (SELECT id FROM business_categories WHERE name = 'Piercer' LIMIT 1)
    WHEN t LIKE '%centro beness%' OR t LIKE '% spa%' THEN (SELECT id FROM business_categories WHERE name = 'Centro benessere' LIMIT 1)
    WHEN t LIKE '%solarium%' THEN (SELECT id FROM business_categories WHERE name = 'Solarium' LIMIT 1)
    -- Animali
    WHEN t LIKE '%toeletta%animal%' OR t LIKE '%pet grooming%' THEN (SELECT id FROM business_categories WHERE name = 'Toelettatura' LIMIT 1)
    WHEN t LIKE '%pension%animal%' OR t LIKE '%kennel%' THEN (SELECT id FROM business_categories WHERE name = 'Pensione animali' LIMIT 1)
    WHEN t LIKE '%addestrat%' THEN (SELECT id FROM business_categories WHERE name = 'Addestratore' LIMIT 1)
    WHEN t LIKE '%dog sit%' OR t LIKE '%dogsit%' THEN (SELECT id FROM business_categories WHERE name = 'Dog Sitter' LIMIT 1)
    WHEN t LIKE '%pet sit%' THEN (SELECT id FROM business_categories WHERE name = 'Pet Sitter' LIMIT 1)
    WHEN t LIKE '%nego%animal%' OR t LIKE '%pet shop%' THEN (SELECT id FROM business_categories WHERE name = 'Negozio animali' LIMIT 1)
    -- Commercio
    WHEN t LIKE '%supermerc%' OR t LIKE '%coop%' OR t LIKE '%conad%' OR t LIKE '%esselunga%' OR t LIKE '%carrefour%' THEN (SELECT id FROM business_categories WHERE name = 'Supermercato' LIMIT 1)
    WHEN t LIKE '%alimentar%' OR t LIKE '%minimark%' THEN (SELECT id FROM business_categories WHERE name = 'Alimentari' LIMIT 1)
    WHEN t LIKE '%ferrament%' OR t LIKE '%bricolage%' OR t LIKE '%fai da te%' THEN (SELECT id FROM business_categories WHERE name = 'Ferramenta' LIMIT 1)
    WHEN t LIKE '%abbigli%' OR t LIKE '%moda%' OR t LIKE '%boutique%' OR t LIKE '%vest%' THEN (SELECT id FROM business_categories WHERE name = 'Abbigliamento' LIMIT 1)
    WHEN t LIKE '%calzat%' OR t LIKE '%scarpe%' OR t LIKE '%shoe%' THEN (SELECT id FROM business_categories WHERE name = 'Calzature' LIMIT 1)
    WHEN t LIKE '%gioiell%' OR t LIKE '%jewel%' OR t LIKE '%orefic%' THEN (SELECT id FROM business_categories WHERE name = 'Gioielleria' LIMIT 1)
    WHEN t LIKE '%ottica%' OR t LIKE '%occhial%' THEN (SELECT id FROM business_categories WHERE name = 'Ottica' LIMIT 1)
    WHEN t LIKE '%libr%' OR t LIKE '%book%' THEN (SELECT id FROM business_categories WHERE name = 'Libreria' LIMIT 1)
    WHEN t LIKE '%cartoler%' THEN (SELECT id FROM business_categories WHERE name = 'Cartoleria' LIMIT 1)
    WHEN t LIKE '%arred%' OR t LIKE '%mobili%' OR t LIKE '%furniture%' THEN (SELECT id FROM business_categories WHERE name = 'Arredamento' LIMIT 1)
    WHEN t LIKE '%casaling%' THEN (SELECT id FROM business_categories WHERE name = 'Casalinghi' LIMIT 1)
    WHEN t LIKE '%telefon%' OR t LIKE '%tim shop%' OR t LIKE '%vodafone%' OR t LIKE '%wind%' THEN (SELECT id FROM business_categories WHERE name = 'Telefonia' LIMIT 1)
    WHEN t LIKE '%elettronic%' OR t LIKE '%computer%' THEN (SELECT id FROM business_categories WHERE name = 'Elettronica' LIMIT 1)
    WHEN t LIKE '%fior%' OR t LIKE '%floric%' OR t LIKE '%viva%' THEN (SELECT id FROM business_categories WHERE name = 'Fiorista' LIMIT 1)
    WHEN t LIKE '%tabacch%' THEN (SELECT id FROM business_categories WHERE name = 'Tabaccheria' LIMIT 1)
    -- Informatica
    WHEN t LIKE '%web develop%' OR t LIKE '%sviluppatore web%' THEN (SELECT id FROM business_categories WHERE name = 'Web Developer' LIMIT 1)
    WHEN t LIKE '%software develop%' THEN (SELECT id FROM business_categories WHERE name = 'Software Developer' LIMIT 1)
    WHEN t LIKE '%app develop%' THEN (SELECT id FROM business_categories WHERE name = 'App Developer' LIMIT 1)
    WHEN t LIKE '%web design%' THEN (SELECT id FROM business_categories WHERE name = 'Web Designer' LIMIT 1)
    WHEN t LIKE '%ux/ui%' OR t LIKE '%ux design%' OR t LIKE '%ui design%' THEN (SELECT id FROM business_categories WHERE name = 'UX/UI Designer' LIMIT 1)
    WHEN t LIKE '%sistemist%' THEN (SELECT id FROM business_categories WHERE name = 'Sistemista' LIMIT 1)
    WHEN t LIKE '%cybersecurity%' THEN (SELECT id FROM business_categories WHERE name = 'Cybersecurity' LIMIT 1)
    WHEN t LIKE '%assistenza informatic%' OR t LIKE '%riparazione pc%' THEN (SELECT id FROM business_categories WHERE name = 'Assistenza informatica' LIMIT 1)
    WHEN t LIKE '%riparazione smartphone%' OR t LIKE '%riparazione cellul%' THEN (SELECT id FROM business_categories WHERE name = 'Riparazione smartphone' LIMIT 1)
    -- Marketing
    WHEN t LIKE '%social media%' THEN (SELECT id FROM business_categories WHERE name = 'Social Media Manager' LIMIT 1)
    WHEN t LIKE '%seo%' THEN (SELECT id FROM business_categories WHERE name = 'SEO Specialist' LIMIT 1)
    WHEN t LIKE '%copywriter%' THEN (SELECT id FROM business_categories WHERE name = 'Copywriter' LIMIT 1)
    WHEN t LIKE '%graphic design%' OR t LIKE '%grafico%' THEN (SELECT id FROM business_categories WHERE name = 'Graphic Designer' LIMIT 1)
    WHEN t LIKE '%fotograf%' THEN (SELECT id FROM business_categories WHERE name = 'Fotografo' LIMIT 1)
    WHEN t LIKE '%videomak%' THEN (SELECT id FROM business_categories WHERE name = 'Videomaker' LIMIT 1)
    WHEN t LIKE '%influencer%' THEN (SELECT id FROM business_categories WHERE name = 'Influencer' LIMIT 1)
    WHEN t LIKE '%content creator%' THEN (SELECT id FROM business_categories WHERE name = 'Content Creator' LIMIT 1)
    WHEN t LIKE '%youtuber%' THEN (SELECT id FROM business_categories WHERE name = 'YouTuber' LIMIT 1)
    WHEN t LIKE '%tiktok%' THEN (SELECT id FROM business_categories WHERE name = 'TikToker' LIMIT 1)
    WHEN t LIKE '%streamer%' OR t LIKE '%twitch%' THEN (SELECT id FROM business_categories WHERE name = 'Streamer' LIMIT 1)
    WHEN t LIKE '%blogger%' THEN (SELECT id FROM business_categories WHERE name = 'Blogger' LIMIT 1)
    WHEN t LIKE '%podcast%' THEN (SELECT id FROM business_categories WHERE name = 'Podcaster' LIMIT 1)
    -- Trasporti
    WHEN t LIKE '%corrier%' OR t LIKE '%spedizion%' THEN (SELECT id FROM business_categories WHERE name = 'Corriere' LIMIT 1)
    WHEN t LIKE '%autotrasp%' THEN (SELECT id FROM business_categories WHERE name = 'Autotrasportatore' LIMIT 1)
    WHEN t LIKE '%logistic%' THEN (SELECT id FROM business_categories WHERE name = 'Logistica' LIMIT 1)
    WHEN t LIKE '%taxi%' THEN (SELECT id FROM business_categories WHERE name = 'Taxi' LIMIT 1)
    WHEN t LIKE '%ncc%' THEN (SELECT id FROM business_categories WHERE name = 'NCC' LIMIT 1)
    WHEN t LIKE '%bus%' OR t LIKE '%autobus%' THEN (SELECT id FROM business_categories WHERE name = 'Trasporto persone' LIMIT 1)
    -- Agricoltura
    WHEN t LIKE '%azienda agric%' THEN (SELECT id FROM business_categories WHERE name = 'Azienda agricola' LIMIT 1)
    WHEN t LIKE '%vivai%' OR t LIKE '%vivaist%' THEN (SELECT id FROM business_categories WHERE name = 'Vivaio' LIMIT 1)
    WHEN t LIKE '%floricolt%' THEN (SELECT id FROM business_categories WHERE name = 'Floricoltura' LIMIT 1)
    WHEN t LIKE '%allev%' THEN (SELECT id FROM business_categories WHERE name = 'Allevamento' LIMIT 1)
    WHEN t LIKE '%apicolt%' THEN (SELECT id FROM business_categories WHERE name = 'Apicoltura' LIMIT 1)
    WHEN t LIKE '%cantin%' OR t LIKE '%winery%' THEN (SELECT id FROM business_categories WHERE name = 'Cantina' LIMIT 1)
    WHEN t LIKE '%franto%' THEN (SELECT id FROM business_categories WHERE name = 'Frantoio' LIMIT 1)
    -- Finanza
    WHEN t LIKE '%banc%' OR t LIKE '%bank%' THEN (SELECT id FROM business_categories WHERE name = 'Banca' LIMIT 1)
    WHEN t LIKE '%assicuraz%' THEN (SELECT id FROM business_categories WHERE name = 'Assicurazione' LIMIT 1)
    WHEN t LIKE '%pratiche auto%' THEN (SELECT id FROM business_categories WHERE name = 'Agenzia pratiche auto' LIMIT 1)
    WHEN t LIKE '%patronat%' THEN (SELECT id FROM business_categories WHERE name = 'Patronato' LIMIT 1)
    WHEN t LIKE '%agenzia finanzi%' THEN (SELECT id FROM business_categories WHERE name = 'Agenzia finanziaria' LIMIT 1)
    -- Immobiliare
    WHEN t LIKE '%immobili%' THEN (SELECT id FROM business_categories WHERE name = 'Agenzia immobiliare' LIMIT 1)
    WHEN t LIKE '%architet%' THEN (SELECT id FROM business_categories WHERE name = 'Architetto' LIMIT 1)
    WHEN t LIKE '%ingegn%' THEN (SELECT id FROM business_categories WHERE name = 'Ingegnere' LIMIT 1)
    WHEN t LIKE '%geometr%' THEN (SELECT id FROM business_categories WHERE name = 'Geometra' LIMIT 1)
    WHEN t LIKE '%interior design%' THEN (SELECT id FROM business_categories WHERE name = 'Interior Designer' LIMIT 1)
    WHEN t LIKE '%amministr%condomin%' THEN (SELECT id FROM business_categories WHERE name = 'Amministratore condominiale' LIMIT 1)
    -- Formazione
    WHEN t LIKE '%scuol%' AND NOT t LIKE '%autoscuol%' THEN (SELECT id FROM business_categories WHERE name = 'Scuola' LIMIT 1)
    WHEN t LIKE '%univers%' THEN (SELECT id FROM business_categories WHERE name = 'Università' LIMIT 1)
    WHEN t LIKE '%scuol%lingu%' THEN (SELECT id FROM business_categories WHERE name = 'Scuola lingue' LIMIT 1)
    WHEN t LIKE '%tutor%' OR t LIKE '%ripetiz%' THEN (SELECT id FROM business_categories WHERE name = 'Tutor' LIMIT 1)
    WHEN t LIKE '%formaz%prof%' THEN (SELECT id FROM business_categories WHERE name = 'Formazione professionale' LIMIT 1)
    -- Arte e Spettacolo
    WHEN t LIKE '%cantant%' THEN (SELECT id FROM business_categories WHERE name = 'Cantante' LIMIT 1)
    WHEN t LIKE '%dj%' OR t LIKE '%disc jockey%' THEN (SELECT id FROM business_categories WHERE name = 'DJ' LIMIT 1)
    WHEN t LIKE '%wedding plan%' THEN (SELECT id FROM business_categories WHERE name = 'Wedding Planner' LIMIT 1)
    WHEN t LIKE '%organ%event%' THEN (SELECT id FROM business_categories WHERE name = 'Organizzatore eventi' LIMIT 1)
    -- Sport
    WHEN t LIKE '%palestr%' OR t LIKE '%gym%' OR t LIKE '%fitness%' THEN (SELECT id FROM business_categories WHERE name = 'Palestra' LIMIT 1)
    WHEN t LIKE '%personal train%' THEN (SELECT id FROM business_categories WHERE name = 'Personal Trainer' LIMIT 1)
    WHEN t LIKE '%piscin%' THEN (SELECT id FROM business_categories WHERE name = 'Piscina' LIMIT 1)
    WHEN t LIKE '%yoga%' THEN (SELECT id FROM business_categories WHERE name = 'Yoga' LIMIT 1)
    WHEN t LIKE '%pilates%' THEN (SELECT id FROM business_categories WHERE name = 'Pilates' LIMIT 1)
    WHEN t LIKE '%crossfit%' THEN (SELECT id FROM business_categories WHERE name = 'CrossFit' LIMIT 1)
    WHEN t LIKE '%scuol%danz%' OR t LIKE '%danza%' THEN (SELECT id FROM business_categories WHERE name = 'Scuola danza' LIMIT 1)
    WHEN t LIKE '%arti marzial%' OR t LIKE '%karate%' OR t LIKE '%jud%' THEN (SELECT id FROM business_categories WHERE name = 'Arti marziali' LIMIT 1)
    -- Enti
    WHEN t LIKE '%comun%' AND t LIKE '%municip%' THEN (SELECT id FROM business_categories WHERE name = 'Comune' LIMIT 1)
    WHEN t LIKE '%fondaz%' THEN (SELECT id FROM business_categories WHERE name = 'Fondazione' LIMIT 1)
    WHEN t LIKE '%onlus%' THEN (SELECT id FROM business_categories WHERE name = 'ONLUS' LIMIT 1)
    WHEN t LIKE '%assoc%sport%' THEN (SELECT id FROM business_categories WHERE name = 'Associazione sportiva' LIMIT 1)
    WHEN t LIKE '%assoc%' THEN (SELECT id FROM business_categories WHERE name = 'Associazione culturale' LIMIT 1)
    -- Infanzia
    WHEN t LIKE '%asilo%' OR t LIKE '%nido%' THEN (SELECT id FROM business_categories WHERE name = 'Asilo nido' LIMIT 1)
    WHEN t LIKE '%baby sit%' OR t LIKE '%babysit%' THEN (SELECT id FROM business_categories WHERE name = 'Baby Sitter' LIMIT 1)
    WHEN t LIKE '%ludotec%' THEN (SELECT id FROM business_categories WHERE name = 'Ludoteca' LIMIT 1)
    WHEN t LIKE '%educat%' THEN (SELECT id FROM business_categories WHERE name = 'Educatore' LIMIT 1)
    WHEN t LIKE '%centro estiv%' OR t LIKE '%grest%' THEN (SELECT id FROM business_categories WHERE name = 'Centro estivo' LIMIT 1)
    -- Assistenza
    WHEN t LIKE '%badant%' THEN (SELECT id FROM business_categories WHERE name = 'Badante' LIMIT 1)
    WHEN t LIKE '%casa di riposo%' OR t LIKE '%rsa%' OR t LIKE '%residenza sanit%' THEN (SELECT id FROM business_categories WHERE name = 'Casa di riposo' LIMIT 1)
    WHEN t LIKE '%assist%domicil%' THEN (SELECT id FROM business_categories WHERE name = 'Assistenza domiciliare' LIMIT 1)
    -- Media
    WHEN t LIKE '%radio%' THEN (SELECT id FROM business_categories WHERE name = 'Radio' LIMIT 1)
    WHEN t LIKE '%casa editr%' OR t LIKE '%editrice%' THEN (SELECT id FROM business_categories WHERE name = 'Casa editrice' LIMIT 1)
    WHEN t LIKE '%tipograf%' OR t LIKE '%stampa%' THEN (SELECT id FROM business_categories WHERE name = 'Tipografia' LIMIT 1)
    WHEN t LIKE '%agenzia pubbl%' OR t LIKE '%advertising%' THEN (SELECT id FROM business_categories WHERE name = 'Agenzia pubblicitaria' LIMIT 1)
    -- Ricerca
    WHEN t LIKE '%laborat%anal%' OR t LIKE '%analisi clin%' THEN (SELECT id FROM business_categories WHERE name = 'Laboratorio analisi' LIMIT 1)
    WHEN t LIKE '%laborat%odontotec%' THEN (SELECT id FROM business_categories WHERE name = 'Laboratorio odontotecnico' LIMIT 1)
    WHEN t LIKE '%laborat%chim%' THEN (SELECT id FROM business_categories WHERE name = 'Laboratorio chimico' LIMIT 1)
    WHEN t LIKE '%centro ricerc%' THEN (SELECT id FROM business_categories WHERE name = 'Centro ricerca' LIMIT 1)
    -- Energia
    WHEN t LIKE '%fornitor%luce%' OR t LIKE '%fornitor%gas%' THEN (SELECT id FROM business_categories WHERE name = 'Fornitore luce e gas' LIMIT 1)
    WHEN t LIKE '%colonn%ricar%' OR t LIKE '%charging station%' THEN (SELECT id FROM business_categories WHERE name = 'Installatore colonnine elettriche' LIMIT 1)
    WHEN t LIKE '%energy manager%' THEN (SELECT id FROM business_categories WHERE name = 'Energy Manager' LIMIT 1)
    WHEN t LIKE '%comunit%energ%' THEN (SELECT id FROM business_categories WHERE name = 'Comunità energetica' LIMIT 1)
    -- Servizi Digitali
    WHEN t LIKE '%hosting%' THEN (SELECT id FROM business_categories WHERE name = 'Hosting' LIMIT 1)
    WHEN t LIKE '%cloud%' THEN (SELECT id FROM business_categories WHERE name = 'Cloud' LIMIT 1)
    WHEN t LIKE '%saas%' THEN (SELECT id FROM business_categories WHERE name = 'SaaS' LIMIT 1)
    WHEN t LIKE '%blockchain%' THEN (SELECT id FROM business_categories WHERE name = 'Blockchain' LIMIT 1)
    WHEN t LIKE '%consulenz%digital%' THEN (SELECT id FROM business_categories WHERE name = 'Consulenza digitale' LIMIT 1)
    WHEN t LIKE '%e-commerce%' OR t LIKE '%ecommerce%' THEN (SELECT id FROM business_categories WHERE name = 'Sviluppo e-commerce' LIMIT 1)
    ELSE NULL
  END;
  RETURN cat_id;
END;
$$;
